# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:

- script: |

    echo Add other tasks to build, test, and deploy your project.

    echo See https://aka.ms/yaml

    echo salesforce cli install

    sudo npm install -g sfdx-cli

  displayName: 'Run a multi-line script and install salesforce cli'
- bash: |

   sfdx force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --jwtkeyfile ./buildfiles/server.key --username ${HUB_ORG} --instanceurl ${SFDC_HOST} --setdefaultdevhubusername

  displayName:  authenticate with dev hub

- bash: |

   sfdx force:mdapi:deploy -p "/force-app/main/default" -u ${HUB_ORG}

  displayName: Deploy manifest  



